# Generated by Django 5.1 on 2024-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenoasis', '0002_alter_image_options_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
