# Generated by Django 5.1 on 2024-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenoasis', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
