# Generated by Django 5.1 on 2024-11-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenoasis', '0008_remove_feedback_name_feedback_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
